service/urls.py
from django.urls import path
from rest_framework import permissions
from drf_yasg.views import get_schema_view
from drf_yasg import openapi
from . import views
from .views import add_machine, add_maintenance, add_complaint
from .views import ReferenceCreateView, ReferenceListView, ReferenceUpdateView
from .views import EditMaintenanceView
from django.contrib.auth.views import LogoutView

app_name = 'service' 


schema_view = get_schema_view(
    openapi.Info(
        title="Сервис Силант API",
        default_version='v1',
        description="Документация API для сервиса Силант",
        terms_of_service="https://www.google.com/policies/terms/",
        contact=openapi.Contact(email="contact@silant.local"),
        license=openapi.License(name="BSD License"),
    ),
    public=True,
    permission_classes=(permissions.AllowAny,),
)

urlpatterns = [
    path('', views.WelcomeView.as_view(), name='welcome'),
    path('logout/', LogoutView.as_view(next_page='welcome'), name='logout'),
    path('redoc/', schema_view.with_ui('redoc', cache_timeout=0), name='schema-redoc'),
    path('machines/', views.MachineListView.as_view(), name='machine_list'),
    path('maintenance/',views. MaintenanceListView.as_view(), name='maintenance_list'),
    path('complaints/',views. ComplaintListView.as_view(), name='complaint_list'),
    path('request_signup/',views. RequestSignupView.as_view(), name='request_signup'),
    path('machine/<int:pk>/',views. MachineDetailView.as_view(), name='machine_detail'),
    path('machines/add/', add_machine, name='add_machine'),
    path('maintenance/add/', add_maintenance, name='add_maintenance'),
    path('complaints/add/', add_complaint, name='add_complaint'),
    path('machine/<int:pk>/edit/', views.EditMachineView.as_view(), name='edit_machine'),
    path('maintenance/<int:pk>/edit/', EditMaintenanceView.as_view(), name='edit_maintenance'),
    path('complaint/<int:pk>/edit/', views.EditComplaintView.as_view(), name='edit_complaint'),
    path('references/add/', ReferenceCreateView.as_view(), name='reference_add'),
    path('references/', ReferenceListView.as_view(), name='reference_list'),
    path('references/<int:pk>/edit/', ReferenceUpdateView.as_view(), name='reference_edit'),

]

silant/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView
from django.views.generic import TemplateView
from django.contrib.auth.views import LogoutView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/service/', include('service.urls')),
    path('', RedirectView.as_view(url='/api/service/')),
    path('welcome/', TemplateView.as_view(template_name='welcome.html'), name='welcome'),
    path('accounts/', include('allauth.urls')),
    path('logout/', LogoutView.as_view(next_page='welcome'), name='logout'),
]

service/forms.py
from django import forms
from .models import Machine, Maintenance, Complaint, Reference

class FactoryNumberForm(forms.Form):
    factory_number = forms.CharField(label='Заводской номер', max_length=100)


class MachineForm(forms.ModelForm):
    class Meta:
        model = Machine
        fields = "__all__"
        widgets = {
            'shipment_date': forms.DateInput(attrs={'type': 'date'}),
        }

class MaintenanceForm(forms.ModelForm):
    class Meta:
        model = Maintenance
        fields = "__all__"
        widgets = {
            'maintenance_date': forms.DateInput(attrs={'type': 'date'}),
        }

    def __init__(self, *args, **kwargs):
        user = kwargs.pop('user')
        super().__init__(*args, **kwargs)
        role = user.userprofile.role

        if role == 'pr':
            pass  
        elif role == 'mn':
            self.fields['machine'].queryset = Machine.objects.filter(service_company=user)
        elif role == 'ex':
            self.fields['machine'].queryset = Machine.objects.filter(client=user)
        else:  
            self.fields['machine'].queryset = Machine.objects.none()
            
              
class ComplaintForm(forms.ModelForm):
    class Meta:
        model = Complaint
        fields = "__all__"
        widgets = {
            'claim_date': forms.DateInput(attrs={'type': 'date'}),
        }

    def __init__(self, *args, **kwargs):
        user = kwargs.pop('user')
        super().__init__(*args, **kwargs)
        role = user.userprofile.role

        if role == 'pr':
            pass  
        elif role == 'mn':
            self.fields['machine'].queryset = Machine.objects.filter(service_company=user)
        elif role == 'ex':
            self.fields['machine'].queryset = Machine.objects.filter(client=user)
        else:  
            self.fields['machine'].queryset = Machine.objects.none()
            
            

class ReferenceForm(forms.ModelForm):
    class Meta:
        model = Reference
        fields = ['entity_name', 'name', 'description']

service/views.py
from .models import Reference
from rest_framework import viewsets
from .forms import FactoryNumberForm, MachineForm, MaintenanceForm, ComplaintForm, ReferenceForm
from .models import Machine, Maintenance, Complaint, Reference
from .serializers import MachineSerializer, MaintenanceSerializer, ComplaintSerializer, ReferenceSerializer
from django.http import HttpResponseForbidden
from django.views.generic import ListView, TemplateView, DetailView, CreateView
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render,get_object_or_404, redirect
from django.views import View
from django.views.generic.edit import UpdateView
from django.urls import reverse_lazy
from django.db.models import Q
from django.contrib.auth.mixins import UserPassesTestMixin
from django.urls import reverse_lazy



class WelcomeView(View):
    def get(self, request):
        form = FactoryNumberForm(request.GET)
        machine = None
        error_message = None

        if form.is_bound and form.is_valid():
            factory_number = form.cleaned_data.get('factory_number')
        #if factory_number:
            try:
                machine = Machine.objects.get(factory_number=factory_number)
            except Machine.DoesNotExist:
                error_message = "Машина не найдена."
            except Exception as e:
                error_message = f"Ошибка поиска: {e}"
        return render(request, 'welcome.html', {
            'form': form,
            'error_message': error_message,
            'machine': machine,
        })
        

class MachineListView(LoginRequiredMixin,ListView):
    model = Machine
    template_name = 'service/machine_list.html' 
    context_object_name = 'machines' 

    def dispatch(self, request, *args, **kwargs):
        if not request.user.is_authenticated:
            return redirect('service:request_signup') 
        return super().dispatch(request, *args, **kwargs)
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['references'] = Reference.objects.all()
        return context 
    
    def get_queryset(self):
        user = self.request.user
        if user.userprofile.role in ("ex", 'mn', 'pr'):
            client_machines = Machine.objects.filter(client=user)
            service_company_machines = Machine.objects.filter(service_company=user)
            return client_machines | service_company_machines 
        return Machine.objects.all()


class MaintenanceListView(LoginRequiredMixin, ListView):
    model = Maintenance
    template_name = 'service/maintenance_list.html' 
    context_object_name = 'maintenances' 

    def dispatch(self, request, *args, **kwargs):
        if not request.user.is_authenticated:
            return redirect('service:request_signup') 
        return super().dispatch(request, *args, **kwargs)

    def get_queryset(self):
        user = self.request.user
          
        if user.userprofile.role == 'pr':
            return Maintenance.objects.all().distinct()

        if user.userprofile.role in ("ex", 'mn', 'pr'):
            references = Reference.objects.filter(user=user)

            if user.userprofile.role == 'mn':
                return Maintenance.objects.filter(
                    Q(machine__client_ref__in=references) | 
                    Q(service_company=user)  
                ).distinct()

            return Maintenance.objects.filter(
                Q(machine__client_ref__in=references)            
            ).distinct()

        return Maintenance.objects.none 

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['allowed_roles'] = ["mn", "pr"] 
        return context

    def post(self, request, *args, **kwargs):
        maintenance_id = request.POST.get('maintenance_id')
        if maintenance_id:
            return redirect('service:edit_maintenance', pk=maintenance_id)
        return redirect('service:maintenance_list')


class ComplaintListView(LoginRequiredMixin,ListView):
    model = Complaint
    template_name = 'service/complaint_list.html' 
    context_object_name = 'complaints'  

    def get_queryset(self):
        return Complaint.objects.all().order_by('claim_date')
    
    def dispatch(self, request, *args, **kwargs):
        if not request.user.is_authenticated:
            return redirect('service:request_signup') 
        return super().dispatch(request, *args, **kwargs)
    
    def get_queryset(self):
        user = self.request.user         
        if user.userprofile.role == 'pr':
            return Complaint.objects.all().distinct()
        if user.userprofile.role in ("ex", 'mn', 'pr'):
            references = Reference.objects.filter(user=user)
            if user.userprofile.role == 'mn':
                return Complaint.objects.filter(
                    Q(machine__client_ref__in=references) | 
                    Q(service_company=user)  
                ).distinct()
            return Complaint.objects.filter(
                Q(machine__client_ref__in=references)            
            ).distinct()
        return Complaint.objects.none 
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['allowed_roles'] = ["mn", "pr"] 
        return context
    
    def post(self, request, *args, **kwargs):
        complaint_id = request.POST.get('complaint_id')
        if complaint_id:
            return redirect('service:edit_complaint', pk=complaint_id)
        return redirect('service:complaint_list')


class RequestSignupView(TemplateView):
    template_name = 'service/request_signup.html' 

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context
    
    
class MachineDetailView(DetailView):
    model = Machine
    template_name = 'service/machine_detail.html'
    context_object_name = 'machine'

    def get(self, request, *args, **kwargs):
        machine = self.get_object()
        return render(request, self.template_name, {'machine': machine})
    
    
class EditMachineView(UpdateView,UserPassesTestMixin):
    model = Machine
    fields = ['model', 'engine_model', 'transmission_model', 'front_axle_model', 'rear_axle_model', 'shipment_date']
    template_name = 'service/edit_machine.html'
    success_url = reverse_lazy('service:machine_list')
    
    def test_func(self):
             # return self.request.user.is_authenticated and getattr(self.request.user, 'is_producer', False)           
             return self.request.user.is_authenticated and self.request.user.userprofile.role == 'pr'
    
    def edit_machine(request, pk):
        machine = get_object_or_404(Machine, pk=pk)
        if request.method == 'POST':
            form = MachineForm(request.POST, instance=machine)
            if form.is_valid():
                form.save()
                return redirect('service:machine_detail', pk=machine.pk)
        else:
            form = MachineForm(instance=machine)
        return render(request, 'service/edit_machine.html', {'form': form})
    
    
class EditMaintenanceView(UpdateView):
    model = Maintenance
    fields = "__all__"
    template_name = 'service/edit_maintenance.html'
    success_url = reverse_lazy('service:maintenance_list')

class EditComplaintView(UpdateView):
    model = Complaint
    fields = "__all__"
    template_name = 'service/edit_complaint.html'
    success_url = reverse_lazy('service:complaint_list')


class ReferenceCreateView(CreateView):
    model = Reference
    form_class = ReferenceForm
    template_name = 'service/reference_form.html'
    success_url = reverse_lazy('service:reference_list')
    
class ReferenceUpdateView(UpdateView):
    model = Reference
    form_class = ReferenceForm
    template_name = 'service/reference_form.html'
    success_url = reverse_lazy('service:reference_list')    

class ReferenceListView(ListView):
    model = Reference
    template_name = 'service/reference_list.html'
    context_object_name = 'references'
    
    def get_queryset(self):
        queryset = super().get_queryset()
        query = self.request.GET.get('q') 
        if query:
            queryset = queryset.filter(Q(entity_name__icontains=query) | Q(name__icontains=query))
        return queryset


@login_required
def add_machine(request):
    try:
        role = request.user.userprofile.role
    except AttributeError:
        return HttpResponseForbidden('Профиль пользователя не найден.')

    if role != 'pr':
        return HttpResponseForbidden('Доступ разрешён только производителю.')

    if request.method == 'POST':
        form = MachineForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('service:machine_list') 
    else:
        form = MachineForm()
    return render(request, 'service/add_machine.html', {'form': form})


@login_required
def add_maintenance(request):
    if request.method == 'POST':
        form = MaintenanceForm(request.POST, user=request.user)
        if form.is_valid():
            machine = form.cleaned_data['machine']
            role = request.user.userprofile.role
            access = False
            
            if role == 'pr':
                access = True 
            elif role == 'ex':
                access = (machine.client == request.user) 
            elif role == 'mn':
                access = (machine.service_company == request.user)  
            else:
                access = False 

            if not access:
                form.add_error('machine', 'Нет доступа к выбранной машине')
            else:
                form.save()
                return redirect('service:maintenance_list')
    else:
        form = MaintenanceForm(user=request.user)

    return render(request, 'service/add_maintenance.html', {'form': form})


@login_required

service/templates/service/add_complaint.html
{% extends 'base.html' %}
<head>
{% load static %}

{% block extra_css %}
<link rel="stylesheet" type="text/css" href="{% static 'service/add_complaint.css' %}">
{% endblock %}    
{% block title %}Добавить отказ{% endblock %}
</head>
<body>
{% block content %}
<h1>Добавить отказ</h1>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-primary">Сохранить</button>
    <div class="mb-3">
     <a href="{% url 'service:complaint_list' %}" class="nav-link nav-btn">Назад</a>
 </div>
</form>
{% endblock %}
</body>

service/templates/service/add_machine.html
{% extends 'base.html' %}
{% load static %}

{% block extra_css %}
<link rel="stylesheet" type="text/css" href="{% static 'service/add_machine.css' %}">
{% endblock %}    

{% block title %}Добавить машину{% endblock %}
<body>
{% block content %}
<h1>Добавить машину</h1>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    {% comment %} <form id="referenceForm">
    <input type="text" name="entity_name" placeholder="Название сущности" required>
    <input type="text" name="name" placeholder="Название" required>
    <textarea name="description" placeholder="Описание" required></textarea>
    <button type="submit">Создать</button>
</form> {% endcomment %}
<script>
$('#referenceForm').submit(function(e) {
    e.preventDefault(); 

    $.ajax({
        url: '/api/reference/create/',
        method: 'POST',
        data: $(this).serialize(),
        success: function(data) {
            alert('Запись успешно создана!');
        },
        error: function() {
            alert('Ошибка при создании записи. Попробуйте еще раз.');
        }
    });
});
</script>
    <button type="submit" class="btn btn-primary">Сохранить</button>
     <div class="mb-3">
     <a href="{% url 'service:machine_list' %}" class="nav-link nav-btn">Назад</a>
 </div>
</form>
{% endblock %}
</body>

service/templates/service/complaint_list.html
{% extends 'base.html' %}
<head>
{% load static %}

{% block extra_css %}
<link rel="stylesheet" type="text/css" href="{% static 'service/complaint_list.css' %}">
{% endblock %}    
{% block title %}Список рекламаций{% endblock %}

{% block content %}

</head>
<body>
<div class="client">  
    {% if user.is_authenticated %}
        <div class="user-info">
            <span>Пользователь/{{ user.username }}</span>
        </div>
    {% else %}
        <a href="{% url 'account_login' %}" class="btn-login">
            <button type="button" class="button-class">Войти</button>
        </a>
    {% endif %}
    </div>    
    <div class="info">
        <p>Рекламации</p>
    </div>
    <nav class="navbarnaft">
        <ul>
            <li class="nav-item">
                <a class="nav-link nav-btn" href="{% url 'service:machine_list' %}">Общая информация</a>
            </li>
            <li class="nav-item">
                <a class="nav-link nav-btn" href="{% url 'service:maintenance_list' %}">ТО</a>
            </li>
            <li class="nav-item">
                <a class="nav-link nav-btn" href="{% url 'service:complaint_list' %}">Рекламации</a>
            </li>
        </ul>
     </nav>
<form method="post">
{% comment %} {% csrf_token %} {% endcomment %}
<div class="complaint-table">
<table class="table">
    <thead>
        <tr>
            <th>выбор</th>
            <th>Зав. № машины</th>
            <th>Узел отказа</th>
            <th>Способ восстановления</th>
            <th>Дата отказа</th>
            <th>Дата восстановления</th>
            <th>Сервисная компания</th>  
            <th>Наработка м/часов</th>
            <th>Время простоя техники</th>
            <th>Описание отказа</th>
            <th>Использовавшиеся запчасти </th>
        </tr>
    </thead>
    <tbody>
        {% for complaint in complaints %}
        <tr>
            <td>
                <div class="custom-radio">
                    <input type="radio"  id="complaint{{ complaint.id }}" name="complaint_id" value="{{ complaint.id }}">
                </div>
            </td>
            <td>   {% if complaint.machine %}
        <a href="{% url 'service:machine_detail' complaint.machine.id %}" class="btn btn-primary">
            {{ complaint.machine.factory_number }}
        </a>
           {% else %}
               Нет данных о машине
            {% endif %}</td>
            <td>
                 <a href="#" class="open-reference"
                    data-entity="{{complaint.failure_node_ref.entity_name }}"
                    data-name="{{ complaint.failure_node_ref.name }}" 
                    data-description="{{ complaint.failure_node_ref.description|escapejs }}">
                    {{ complaint.failure_node_ref }}
                </a>
                </td>
            <td>
                <a href="#" class="open-reference"
                    data-entity="{{ complaint.recovery_method_ref.entity_name }}"
                    data-name="{{ complaint.recovery_method_ref.name }}"
                    data-description="{{ complaint.recovery_method_ref.description|escapejs }}">
                    {{ complaint.recovery_method_ref }}
                </a>
            </td>
            <td>{{ complaint.claim_date }}</td>
            <td>{{ complaint.recovery_date }}</td>
            <td>
                 <a href="#" class="open-reference"
                    data-entity="{{ complaint.service_company_ref.entity_name }}"
                    data-name="{{ complaint.service_company_ref.name }}"
                    data-description="{{ complaint.service_company_ref.description|escapejs }}">
                    {{ complaint.service_company_ref }}
                </a>
                </td>
            <td>{{ complaint.operating_hours }}</td>
            <td>{{ complaint.downtime_hours }}</td>
            <td>{{ complaint.failure_description }}</td>
            <td>{{ complaint.spare_parts_used }}</td>
        </tr>
        {% empty %}
        <tr>
            <td colspan="6">Нет данных о рекламациях.</td>
        </tr>
        {% endfor %}
<div class="modal fade" id="referenceModal" tabindex="-1" aria-labelledby="referenceModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="referenceModalLabel">Справочная информация</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Закрыть"></button>
            </div>
            <div class="modal-body">
               <p><strong>Название сущности:</strong> <span id="entityName"></span></p>
                <p><strong>Название:</strong> <span id="referenceName"></span></p>
                <p><strong>Описание:</strong></p>
                <p id="referenceDescription"></p>
            </div>
        </div>
    </div>
</div>
<script>
  $(document).ready(function() {
    $('.open-reference').click(function(e) {
        e.preventDefault();
        const entity = $(this).data('entity');
        const name = $(this).data('name');
        const description = $(this).data('description');

        $('#entityName').text(entity);
        $('#referenceName').text(name);
        $('#referenceDescription').text(description);
        $('#referenceModal').modal('show');
    });
});
</script>

    </tbody>
</table>
</body>
 <div class="mb-3">
     <a href="{% url 'service:add_complaint' %}" class="nav-link nav-btn">Добавить рекламацию</a>
 </div>
 {% if user.userprofile.role in allowed_roles %}
    <button type="submit" class="nav-link nav-btn">Редактировать выбранную рекламацию</button>
{% endif %}
</div>
</form>
{% endblock %}

service/templates/service/edit_complaint.html
{% extends 'base.html' %}
{% load static %}

{% block extra_css %}
<link rel="stylesheet" type="text/css" href="{% static 'service/maintenance_list.css' %}">
{% endblock %}

{% block title %}Добавить машину{% endblock %}

{% block content %}
<h1>Редактирование данных рекламации</h1>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-primary">Сохранить</button>
</form>
<a href="{% url 'service:complaint_list' %}" class="nav-link nav-btn">Назад</a>
{% endblock %}

service/templates/service/machine_list.html
{% extends 'base.html' %}
<head>
{% load static %}

{% block extra_css %}
<link rel="stylesheet" type="text/css" href="{% static 'service/machine_list.css' %}">
{% endblock %}
{% block title %}Список машин{% endblock %}
</head>
<body>
{% block content %}
<div class="content">
    <div class="client">  
    {% if user.is_authenticated %}
        <div class="user-info">
            <span>Пользователь/{{ user.username }}</span>
        </div>
    {% else %}
        <a href="{% url 'account_login' %}" class="btn-login">
            <button type="button" class="button-class">Войти</button>
        </a>
    {% endif %}
    </div>    
    <div class="info">
        <p>Информация о комплектации и технических характеристиках Вашей техники</p>
    </div>
    <nav class="navbarnaft">
        <ul>
            <li class="nav-item">
                <a class="nav-link nav-btn" href="{% url 'service:machine_list' %}">Общая информация</a>
            </li>
            <li class="nav-item">
                <a class="nav-link nav-btn" href="{% url 'service:maintenance_list' %}">ТО</a>
            </li>
            <li class="nav-item">
                <a class="nav-link nav-btn" href="{% url 'service:complaint_list' %}">Рекламации</a>
            </li>
        </ul>
     </nav>   
<div class="machine-table">
<table class="table">
    <thead>
        <tr>
            <th>Зав. № машины</th>
            <th>Модель техники</th>
            <th>Модель двигателя</th>
            <th>Зав. № двигателя</th>
            <th>Модель трансмиссии</th>
            <th>Зав. № трансмиссии</th>
            <th>Модель ведущего моста</th>
            <th>Зав. № ведущего моста</th>
            <th>Модель управляемого моста</th>
            <th>Зав. № управляемого моста</th>
            <th>Договор поставки №, дата</th>
            <th>Дата отгрузки с завода</th>
            <th>Грузополучатель</th>
            <th>Адрес поставки</th>
            <th>Комплектация</th>
            <th>Клиент</th>
            <th>Сервисная компания</th>
            
        </tr>
    </thead>
    <tbody>
        {% for machine in machines %}
        <tr>
           <td>   {% if machine %}
                <a href="{% url 'service:machine_detail' machine.id %}" class="btn btn-primary">
                    {{ machine.factory_number }}
                </a>
           {% else %}
        Нет данных о машине
            {% endif %}</td>

            <td>
                  <a href="#" class="open-reference"
                    data-entity="{{ machine.model_ref.entity_name }}"
                    data-name="{{ machine.model_ref.name }}"
                    data-description="{{ machine.model_ref.description|escapejs }}">
                    {{ machine.model }}
                    </a>

            </td>
            <td>
                <a href="#" class="open-reference"
                    data-entity="{{ machine.engine_model_ref.entity_name }}"
                    data-name="{{ machine.engine_model_ref.name }}"
                    data-description="{{ machine.engine_model_ref.description|escapejs }}">
                    {{ machine.engine_model }}
                </a>

            </td>
            <td>{{ machine.engine_serial_number }}</td>  
            <td><a href="#" class="open-reference" 
                   data-entity="Модель трансмиссии" 
                   data-name="{{ machine.transmission_model }}" 
                   data-description="{{ machine.transmission_model_ref.description }}"> <!-- Добавляем описание -->
                    {{ machine.transmission_model }}  <!-- Отображаем название модели двигателя -->
                  </a></td>
            <td>{{ machine.transmission_serial_number }}</td> 
            <td>
                 <a href="#" class="open-reference"
                    data-entity="{{ machine.front_axle_model_ref.entity_name }}"
                    data-name="{{ machine.front_axle_model_ref.name }}"
                    data-description="{{ machine.front_axle_model_ref.description|escapejs }}">
                    {{ machine.front_axle_model }}
                </a>
            </td>
            <td>{{ machine.front_axle_serial_number }}</td> 
            <td>  <a href="#" class="open-reference"
                    data-entity="{{ machine.rear_axle_model_ref.entity_name }}"
                    data-name="{{ machine.rear_axle_model_ref.name }}"
                    data-description="{{ machine.rear_axle_model_ref.description|escapejs }}">
                    {{ machine.rear_axle_model }}<!-- Отображаем название модели двигателя -->
                  </a>
                </td>
            <td>{{ machine.rear_axle_serial_number }}</td>  
            <td>{{ machine.supply_contract_number }}</td> 
            <td>{{ machine.shipment_date }}</td>
            <td>{{ machine.consignee }}</td> 
            <td>{{ machine.delivery_address }}</td>  
            <td>{{ machine.equipment }}</td>  
            <td>{{ machine.client_ref }}</td>  
            <td><a href="#" class="open-reference"
                    data-entity="{{ machine.service_company_ref.entity_name }}"
                    data-name="{{ machine.service_company_ref.name }}"
                    data-description="{{ machine.service_company_ref.description|escapejs }}">
                {{ machine.service_company_ref }}</td>  
            
        </tr>
        {% empty %}
        <tr>
            <td colspan="17">Нет данных</td>
        </tr>
        {% endfor %}

<!-- Модальное окно -->
<div class="modal fade" id="referenceModal" tabindex="-1" aria-labelledby="referenceModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="referenceModalLabel">Справочная информация</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Закрыть"></button>
            </div>
            <div class="modal-body">
               <p><strong>Название сущности:</strong> <span id="entityName"></span></p>
                <p><strong>Название:</strong> <span id="referenceName"></span></p>
                <p><strong>Описание:</strong></p>
                <p id="referenceDescription"></p>
            </div>
        </div>
    </div>
</div>
<script>
  $(document).ready(function() {
    $('.open-reference').click(function(e) {
        e.preventDefault();
        const entity = $(this).data('entity');
        const name = $(this).data('name');
        const description = $(this).data('description');

        $('#entityName').text(entity);
        $('#referenceName').text(name);
        $('#referenceDescription').text(description);
        $('#referenceModal').modal('show');
    });
});
</script>



    </tbody>
</table>
<div class="mb-3">
    {% if user.is_authenticated and user.userprofile.role == 'pr' %}
        <a href="{% url 'service:add_machine' %}" class="nav-link nav-btn">Добавить машину</a>
    {% endif %}
</div>

<div class="mb-3">
    {% if user.is_authenticated and user.userprofile.role == 'pr' %}
        <a href="{% url 'service:reference_list' %}" class="nav-link nav-btn">Редактировать справочники</a>
    {% endif %}
</div>

</div>
</div>
{% endblock %}
</body>

service/templates/service/reference_list.html
{% extends 'base.html' %}
{% load static %}

{% block extra_css %}
<link rel="stylesheet" type="text/css" href="{% static 'service/maintenance_list.css' %}">
{% endblock %}

{% block title %}Справочники{% endblock %}

{% block content %}
<h1>Справочники</h1>

<form method="get">
    <input type="text" name="q" placeholder="Поиск по названию" value="{{ request.GET.q }}">
    <button type="submit">Поиск</button>
</form>

<table class="table">
    <thead>
        <tr>
            <th>Название сущности</th>
            <th>Название</th>
            <th>Описание</th>
            <th>Действия</th> 
        </tr>
    </thead>
    <tbody>
        {% for reference in references %}
        <tr>
            <td>{{ reference.entity_name }}</td>
            <td>{{ reference.name }}</td>
            <td>{{ reference.description }}</td>
            <td>
                <a href="{% url 'service:reference_edit' reference.id %}" class="btn btn-warning">Редактировать</a>
            </td>
        </tr>
        {% empty %}
        <tr>
            <td colspan="4">Нет результатов для отображения.</td>
        </tr>
        {% endfor %}
    </tbody>
</table>

<a href="{% url 'service:reference_add' %}" class="btn btn-primary">Создать новый справочник</a>  <!-- Кнопка для создания нового справочника -->
<div class="mb-3">
     <a href="{% url 'service:machine_list' %}" class="nav-link nav-btn">Назад</a>
 </div>
{% endblock %}